### ISSUE TITLE
n.each is not a function

### ISSUE THREAD

**Issue by adamxp12** [arvgta/ajaxify#109]
Ok let me start by saying that when I get this working it will be an absolute life saver as I need it for a big project I am working on.

But I am having a bit of an issue in that it does absolutely nothing, using it with jQuery 2.2.2 btw, no console logs or anything and this is with the example call on 4nf.org

I tried manually calling it by putting  jQuery().ajaxify("http://127.0.0.1:3000/login"); into the console but it just returns saying n.each is not a function

not sure what I am doing wrong, I have included the library, added the call to my main JS file in the ready function but it just acts like a normal website, and yes I do have a container with an ID of content so I honestly can't see what I am doing wrong?

**Comment by arvgta** [comment]
Do you have a link to your (test) site?  Logging messages on 4nf.org are turned off at the moment, as I'm going on a holiday leave and thought they might irritate the typical visitor.  I could turn them back on quickly, if you wish....

EDIT: Please have a look at this [simplest plugin call](http://4nf.org/interface/#simplest)

The call you're performing:
- `jQuery().ajaxify("http://127.0.0.1:3000/login");`

is _not_ valid
- The content div ID specifier is missing
- instead of options, you're providing a URL string, which leads to undeterminable results

If you would like this issue to be treated discretely, feel free to contact me via eMail: arvgta@gmail.com
(I'm available for the next 10 hours or so)

Finally, thank you for calling Ajaxify a "life saver" - that's what it's there for, to simplify routine Ajax-tasks and potentially save up to hundreds of hours of work!

**Comment by adamxp12** [comment]
Can't really share the site as its a running on a local server as I am in the middle of developing it, might be able to share the HTML and JS files that is being used if that would help.

I have the simplest call already, its got the ID of my content DIV but it did not work, so I tried the public methods at the bottom of the interface page.

Will try turning logging on to see what shows up

**Comment by arvgta** [comment]
Thanks for the quick reply!

I doubt that working on localhost will work at all.
Please try uploading as much as possible to a test site...

**Comment by adamxp12** [comment]
Well yeah that's the issue, tried it on a domain added through the hosts file that pointed to localhost and it started working, guess it don't work unless you have some sort of domain extension

Thanks for your help! this plugin is wicked

**Comment by arvgta** [comment]
My pleasure :)

Feel free to post back, if you run into more trouble...

Best of luck on your project!
