### ISSUE TITLE
suggest to using jquery.history.js

### ISSUE THREAD

**Issue by lloydzhou** [arvgta/ajaxify#13]
This plugin can only using on HTML5 browser.
if using jquery.history.js the HTML4 browser also can using this plugin too.

**Comment by arvgta** [comment]
Hi Lloyd!

Thanks for raising this issue.  It's definitely good for documentation purposes...

I actually tried it out in previous / early versions of this plugin.

However, like Ben Plum, the inventor of Pronto says as well, it introduces too many bugs like this one:

https://github.com/browserstate/history.js/issues/276

There is a great movement to HTML5, so I would rather like to be patient and just support browsers that implement the HTML5 History API correctly.

Beside that, I would have to include the whole file in the shipping, inflating the code.

Finally, the history.js project above is no longer maintained since ages, the bugs not being lifted...

So thanks for the suggestion, but I would like to keep things the way they are, afa HTML5 / HTML4 is concerned.
