### ISSUE TITLE
Prefetch on click and slide in

### ISSUE THREAD

**Issue by cliffstudio** [arvgta/ajaxify#142]
This isn't an issue as such but more of a query as to whether what I'm after is actually do-able within Ajaxify or not. So the end game is to create page transitions a little like this site: http://www.lottanieminen.com

Whereby pages will slide in, I won't need to preview the pages on either side though I'm just wondering whether I could use the 'prefetch' and fetch the page that I've clicked on, push the page content into an element off screen and then slide it into view, if at all possible?

**Comment by arvgta** [comment]
Thanks for the interesting enquiry!  If you're prepared to do some "lower level" work, I could imagine, that it is possible.  A first few words to the built-in features:

- The prefetch is enabled by default anyway!
- However, the prefetch works on `hoverIntent`, not on `click` and the target page is loaded into the built-in cache a bit like the "element off screen" you mentioned.
- The built-in page transitions work on the main content div in a "self-managing" manner, which is probably not, what you want
- The built-in cache  can be addressed easily by writing `$.cache()`
- The main content div can be addressed easily by writing `$.cd("g")`
- After fetching the main content div, you can easily perform your own jQuery `animate()` on it

(the last three features are not yet properly documented on [4nf.org](https://4nf.org/), but at your disposal "out of the box")

<hr />

I had a look at the awesome animations [on the site you quoted](http://www.lottanieminen.com/) and have a first draft of a possible outline in pseudo-code:

- Generate, what you called the "element off screen" first and make it float right of the main content div
- Perform the prefetch and fill the built-in cache
- Load the built-in cache into the "element off screen"
- Animate the main content div to the left with your own `animate()` - the "element off screen" will be animated as well conveniently, due to the float.
- The most difficult step:  Turn the "element off screen" into the main content div

I think the trickiest step is the last one, don't know, how http://www.lottanieminen.com does it?!

Just to get you going - hope that helps for a start!

**Comment by arvgta** [comment]
@nealfletcher : Are you planning to post back, or shall we close this issue?

**Comment by cliffstudio** [comment]
Hi there, apologies for the delay, I've only just seen your response – it seems the notification went to my junk folder. Thanks for your replies, that all sounds positive! I had to achieve it away from ajaxify in the end which isn't ideal...I have another site on at the moment though that needs similarly complex transitions whereby the next page needs to slide over the previous one.

I'm willing to pay for some time spent if you'd be able to provide some code to achieve this?

**Comment by arvgta** [comment]
Hi,

sure, I can try to help you - what do you think of my first post in this thread?
