### ISSUE TITLE
Specify which DIV to swap depending on selector?

### ISSUE THREAD

**Issue by ddaaii** [arvgta/ajaxify#147]
How would I choose which DIVs to replace based on the selector?

Problem:
- If I click link#1, it swaps the #main DIV.
- If I click link#2, it should swap only leftMain. Instead, #main is still swapped.

HTML:
```
<div>
   <div id='left'><a class='loadToMain'>link#1</a></div>
   <div id='main'>
      <div id='leftMain'></div>
      <div id='rightMain'><a class='loadToLeft'>link#2</a></div>
   </div>
</div>
```

jQuery:
```
jQuery('#main').ajaxify({
        selector : ".loadToMain",
    });

jQuery('#leftMain').ajaxify({
        selector : ".loadToLeft",
    });
```

**Comment by arvgta** [comment]
Thanks for your interest in the plugin and the good description, of what you would like to do.  I'm afraid that won't work.

You're right, that this would require mulitplexing of the Ajaxify call, which is not recommended, because each instance of Ajaxify operates on the whole page and they would interfere with each other...
