### ISSUE TITLE
Page transitions "out of the box"

### ISSUE THREAD

**Issue by arvgta** [arvgta/ajaxify#15]
I would like to implement some basic page transitions "out of the box"

The following transition types are supported by [jQuery Mobile](http://demos.jquerymobile.com/1.1.0/docs/pages/page-transitions.html):
- Slide ([squeeze](https://github.com/arvgta/ajaxify/issues/31) implemented instead in order not to break the user's layout)
- Fade (done in #27)
- Pop (done in #28)
- Flip (proposed in #53)
- Slideup
- Slidedown

<hr />

The requirements for a successful implementation are:
- not too much code
- supplied "out of the box", as is the spirit of Ajaxify
- do not break user's layout, i.e. content div effects are self-managing

**Comment by wikiloops** [comment]
since you had this issue on transitions open already, heres another change suggestion:
In its current state, the implemented "fade" is triggered like this:

user clicks -> page is loaded -> fade takes place -> new content is parsed

I'd sugest to change this to

user clicks -> fade triggered -> page is loaded -> new content is parsed

reason why: if the fade does not take place right away, the user has no visual feedback that his click is being processed. If the response takes a little, a user who is used to the fade taking place will likely click again because nothing is happening.
If the fade takes place right away, the user knows his click has been recognized - in the best of cases, it will look just the same as the current version, if the server response takes a little longer, the user will at least know something is happening and not send addittional requests to your sweating server by clicking again.

**Comment by arvgta** [comment]
Hey Wikiloops!

Thanks for all three answers!

The easiest bit first - concerning the simple _fade_ effect:

```
if(fade) $gthis.fadeOut(fade, afterEffect);
```

... a _fadeOut()_ is initiated right after the user click.

Then the content div(s) is switched.

Then a fadeIn() is performed.

The same order is the case for the "slide/squeeze" effect.

Only in the event of a "pop" effect, it is rendered after the content has been switched...

I'll get to the other issues shortly...

Thanks very much!

**Comment by arvgta** [comment]
Please let me know, which other transitions "out of the box" would be useful...

Thanks in advance!

**Comment by arvgta** [comment]
Superseded by #54
