### ISSUE TITLE
[Documentation] jQuery.cache() does not exist

### ISSUE THREAD

**Issue by tchapi** [arvgta/ajaxify#167]
Hi
When I want to clear the memory cache, the documentation says to use :  

      jQuery.cache('f')

Actually, this function does not exist, so the documentation should be changed to : 

      jQuery.cache1('f')

**Comment by arvgta** [comment]
Thanks for your attention to detail!  [Fixed on the page for documenting the memory](https://4nf.org/memory/).  
(I hope that was the only occurrence?)

I renamed the sub-plugin a while ago, because I was educated in the jQuery forum, that `$.cache()` actually is an internal module of jQuery itself and should not be overridden...

**Comment by tchapi** [comment]
Perfect !
