### ISSUE TITLE
Update/copy the body ID similar to the current option "bodyClasses"

### ISSUE THREAD

**Issue by menturion** [arvgta/ajaxify#200]
Feature request. 

In case of the option "`bodyClasses`" is set to `true` Ajaxify updates the classes of the body. However, this script does not support to update the body ID which leads to serious CSS issues for all the sites out there that uses the body ID for CSS selection.

**Comment by arvgta** [comment]
Thanks for that one as well!

Ajaxify currently uses a bespoke `ID `to keep track where the `body `is.  The reason is, that the `body `is escaped to become a normal `div`, but with the above `ID`.  I used to use a bespoke `class `instead, but changed it, in order to at least support swapping of `body `classes.

Maybe not the best choice, as we can see from your proposal...

Which attribute would you suggest to use instead, which can uniquely identify, which `div `is the former `body`?

I could imagine using a bespoke `name `instead?
(unless the next user comes around, asking to support the `body name`...)

**Comment by menturion** [comment]
@arvgta 

Or a data attribute(?).

**Comment by arvgta** [comment]
Great idea!  That's even "softer" and more flexible...

**Comment by arvgta** [comment]
Thanks again.  This may take some time to implement, because it should be done with care...

**Comment by menturion** [comment]
@arvgta 

It would be great to have this fixed, because this can be a big problem for many users who would like to deploy your script.

**Comment by arvgta** [comment]
Alright, I'll do my best, however:

[Could we please handle this issue first](https://github.com/arvgta/ajaxify/issues/199)?

**Comment by arvgta** [comment]
Closing for the moment...  If anyone else needs this feature, please let us know...

**Comment by vijayhardaha** [comment]
Hey,
Any news on implementing data attributes features on body tag?
I am interested in this feature. I was testing Ajaxify with the WordPress theme "Blocksy" so that theme puts some data attributes in the body tag and uses those attributes that apply the CSS.

Since data attributes don't change so I am losing the page design.

**Comment by arvgta** [comment]
Hey, thanks for bringing this up again.

- [I just implemented it](https://github.com/arvgta/ajaxify/blob/new/ajaxify.js)

All attributes of the `body`(except its `ID `- see below) should now be copied...
Please let me know if the fix works!

Please also shout, if you need a completely new version.

If you experience other new issues, this might be due to other changes commited to the above file.
In that case, please let me know and I might be able to make you a completely dedicated version of Ajaxify.

**EDIT: Please note that the ID of the body cannot be copied at the moment.  If you need it to be updated, please let me know...**

**Comment by vijayhardaha** [comment]
Hey @arvgta , Thanks for the quick update. I have tested the new commit version. It works fine. I haven't noticed any issues so far. I will do some more tests and will put a feedback.

**Comment by arvgta** [comment]
Hey, Vijay.  Good news - thanks for posting back!
Yes, please let me know if there are any other issues...
