### ISSUE TITLE
bootstrap 3.2.0, navbar collapse is broken

### ISSUE THREAD

**Issue by danielreiser** [arvgta/ajaxify#22]
Hi Arvind,

thanks a lot for that great js file. It works really well and has a great performance. Unfortunately, it doesn't play well with bootstrap collapsable menus.

Although I set my selector to "a:not(.no-ajax)" ajaxify will prevent toggling the menu.

Any thoughts on that?
Help would be much appreciated!

Thanks a lot!

**Comment by arvgta** [comment]
Hi Daniel,

thanks for raising this issue.
Would you have a link to your site in order to have a look at the behaviour?

I could have a look at it asap...

EDIT:

This is not working on a client I'm using either (without Ajaxify being active) :

http://bootstrapdocs.com/v3.2.0/docs/examples/navbar/

**Comment by danielreiser** [comment]
HI Arvind,

thanks a lot for your reply. I can upload an example page as the page I am currently developing is under NDA. So I'll do that shortly!

**Comment by arvgta** [comment]
Hi Daniel,

yes, thanks.  

But please have a look at the behaviour of this:

http://bootstrapdocs.com/v3.2.0/docs/examples/navbar/

They hotlink to: http://bootstrapdocs.com/v3.2.0/docs/dist/js/bootstrap.min.js, which may be broken at the moment.

Are you hotlinking to the same file?  Does it work for you?

I had a similar enquiry a while ago with a user using "jQuery Mobile" and Ajaxify at the same time.
He suspected an error in Ajaxify where the actual error turned out to be in "jQuery Mobile"...

**Comment by Nurgiel** [comment]
Bootstrap v4.0.0
Mobile navbar collapse button is not working,
Dropdown Menu items are not working.
adding .no-ajaxy class to them isn't helping.

I'm not using boostrap's modal windows but I think those won't work either.

Ajaxify is removing/conflicting with Bootstrap's onClick events.

edit:
including bootstrap.js AFTER ajaxify.js is the solution to a problem
