### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by alexolliveira** [arvgta/ajaxify#235]
I'm trying to use a infinite scrolling on my project:
```
windowOnScroll();
function windowOnScroll() {
  $(window).on("scroll", function(e){
    const {scrollHeight,scrollTop,clientHeight} = document.documentElement
    if (scrollTop + clientHeight > scrollHeight -5){
      if(document.querySelectorAll(".post-item").length < document.getElementById("total_count").value) {
        var lastId = document.querySelectorAll(".post-item");
        var lastchild = lastId[lastId.length-1];
        var id=lastchild.getAttribute("id");
        getMoreData(id);
      }
    }
  });
}
function getMoreData(id) {
  $(window).off("scroll");
  document.querySelector('.ajax-loader').classList.remove("none");
  var formdata=new FormData();
  formdata.append("lastId",id);
  fetch('getMoreData.php',{
    method: 'POST',
    body:formdata
  }).then(function(response){
    response.text().then(function(result){
      setTimeout(function() {
        document.querySelector('.ajax-loader').classList.add("none");
        document.getElementById("post-list").innerHTML+=result;
        windowOnScroll();
      }, 1000);
    })
  }).catch(function(err){ 
    console.error(err);
  });
}
```
To test the script, I do the following steps:

1: I scroll down to load more contents;
2: After, I click on a link to another page;
3: After, I go back to the previous page and scroll down again(step 1);

When I run the code WITHOUT ajaxify, it works fine:
Results:
```
<div class="post-item" id="5">5</div>
<div class="post-item" id="4">4</div>
<div class="post-item" id="3">3</div>
<div class="post-item" id="2">2</div>
<div class="post-item" id="1">1</div>
```

But when I run the code WITH ajaxify, it NOT works fine:
Results:
```
<div class="post-item" id="5">5</div>
<div class="post-item" id="4">4</div>
<div class="post-item" id="3">3</div>
<div class="post-item" id="2">2</div>
<div class="post-item" id="4">4</div>
<div class="post-item" id="3">3</div>
<div class="post-item" id="2">2</div>
<div class="post-item" id="3">3</div>
<div class="post-item" id="2">2</div>
```

Any idea to help?

Config: let myAjaxify=new Ajaxify({elements:"#header,#main", verbosity:2, scrolltop:true, pluginon:!0, requestDelay: 0, intevents: true});
[Link to the Ajaxify I'm using ](https://booge.com.br/static/ajaxify.min.js)

**Comment by arvgta** [comment]
Hi Alex,

Thanks for bringing this up.

I'll get back to you asap, when I have full internet access....


Regards, Arvind

**Comment by arvgta** [comment]
Hi again,

I have read your detailled post several times and don't really have an idea.
Your Ajaxify call is fine.

A few things, that might be helpful though:

- Possibly, your bespoke `fetch()` might be interfering with Ajaxify's central built in `fetch()`?
- Otherwise, it might be yet another timing problem - maybe try changing the `setTimeout()` milliseconds value
- Maybe the new `_won()` function can be helpful? -> See [documentation here](https://4nf.org/events/).  
Quite a few users were successful when hooking into `pronto.render` something like this:

```javascript
_won('pronto.render', function(event){...
}
```

There were some other users recently, that raised the question how Ajaxify can work together with an infinite scroll - so it's a suspenseful topic...


Thanks again and sorry that I can't seem to put my finger on it right away...

<hr>

EDIT: After looking at your code some more, it is quite clear, that this line is faltering in conjunction with Ajaxify:

```javascript
document.getElementById("post-list").innerHTML+=result;
```

...that's to say, that...

- `result` 

...contains the wrong value at that moment in time?

**Comment by alexolliveira** [comment]
@arvgta You were really right, buddy. The problem was in the  setTimeout. I already fixed it, and now it works nice. 
**I would like to apologize for spending your time helping me with a problem that wasn't even in your project**. **My sincere apologies**🙏

**Comment by arvgta** [comment]
Hi Alex,

Glad you got it going.  No need to apologise - that's what this repository and its issues are for!

All the best!
