### ISSUE TITLE
Can you explain the use case of https://4nf.org/pronto/ ?

### ISSUE THREAD

**Issue by khanakia** [arvgta/ajaxify#236]
Hi,

I am trying to understand what is the use of Pronto. 

Can you provide some use case where it is useful ?

Thanks

**Comment by arvgta** [comment]
Hi Aman,

Thanks for bringing this up.
Obviously, the documentation needs some more clarification.

Usage of Pronto events is not mandatory. If your site works without them,
forget about them.

One of the classic use cases is to hook into e.g. "pronto.render" and do
some kind of post-processing in JavaScript.

They're also convenient because you have control of the exact timing.

Maybe you can specify a bit more what it is exactly, that you don't
understand?


Thanks and regards, Arvind

**Comment by khanakia** [comment]
Hello Arvind,

Nothing specific. I was just reading the ajaxify docs and was trying to learn the concept of pronto. What is it exactly and where we can make use of it?

Thanks

**Comment by arvgta** [comment]
Hi Aman,

What you mean is that the giving of custom names for the events is be silly?

The Pronto module, generally speaking takes care of the timing of the rest of Ajaxify. 

Or do mean, that the Pronto events are superfluous because of the native events

**Comment by khanakia** [comment]
No, you misunderstood. All I wanted to know or have some example of pronto for better understanding. That's all

**Comment by arvgta** [comment]
Really, it depends what you want to do...
