### ISSUE TITLE
SyntaxError: missing ) after condition - Inline Script

### ISSUE THREAD

**Issue by faisalrehmanid** [arvgta/ajaxify#29]
Dear Sir,

First of all Thanks for wonderful and amazing plugin. 

I have found one bug When calling inline script after ajax request complete and  if script contains any < > or logical operator like && it gives an error alert message SyntaxError: missing ) after condition 

Woeps has also mention in his comments check following:

https://github.com/arvgta/ajaxify/issues/16

"When the following kind of script gets included into a site which ajaxify tries to fetch, it puts out the catch-alert() containing SyntaxError: missing ) after condition"

Issue is with logical operators. When I load page without ajaxify script working perfectly but when calling using ajaxify inline script it gives the above error.

Kindly look into the issue I will be very thankful to you.

Thanks
Best Regards
Faisal Rehman
faisalrehmanid@hotmail.com

**Comment by arvgta** [comment]
Dear Sir,

thanks for raising this - I had forgotten about it in the meantime.
We seem to agree that the following code is the culprit:

```
        function _addtext(t) {
        try {
            $.globalEval(t);
        } catch (e) {
            alert(e);
        }
        }
```

that's to say, the

```
$.globalEval(t);
```

Unfortunately, the documentation of the above method is not very extensive:
- http://api.jquery.com/jquery.globaleval/

Also, brief research on the web was not fruitful - $.globalEval seems to be an exotic function - rarely used.

I'm clueless at the moment, but can try to raise a thread at http://forum.jquery.com/

@woeps - if you're still around buddy, would you like to join-in the discussion?

@faisalrehmanid - could you verify, that the bug can be re-produced in all browsers?

Thanks!

**Comment by arvgta** [comment]
I've tweaked this file: http://4nf.org/ajaxify.js to use a normal:

```
eval(t)
```

...instead.

It seems to work alright for my sites - please test...

Thanks!

**Comment by woeps** [comment]
Ah, yes. i hardly remembered this one.
By the time of my issue I didn't know the reason for the warning, but I managed to edit my logic in a way, which was accepted without warnings.

I havent't ever used $.globalEval(), which is why I can't give any comments regarding this function.

But I'd be glad to checkout your new code on sunday and report back here.
_(I'm also excited about your implementation of transitions, cause I had to code it myself in the past.)_

**Comment by arvgta** [comment]
@woeps - thanks for joining-in!  Much appreciated!  Bypassing the bug by changing the inline script logic should be a method of last choice...

@faisalrehmanid - could you test it today or otherwise please drop a note if you can't - then I'll build a test case...

As mentioned before - the tweaked file is : 
- http://4nf.org/ajaxify.js

EDIT: Just performed a tiny little test-case with the following inline scripts:

```
if(1 >= 0 ) alert('Success'); 
```

and

```
if(1>=0) alert('Success');
```

and

```
if(pass>0) alert('Success');
```

and

```
if(pass > 0) alert('Success');
```

...which works in all cases, whether using $.globalEval() or eval().  So I haven't, so far, succeeded in re-producing the bug at all...

Cheers!

**Comment by woeps** [comment]
I'm currently very short on time.. (studies, work, etc) - So I wasn't able to fully test everything I wanted to.
But I tested the new script by inserting simple logic and comparison-operations in my latest version on the repo of my project and **it worked like it should**.
I hope to find some time by the end of the week to find some older versions of my inline-scripts in my repo (which contained the logic-operations in question) to test the new script throughly with.

**Comment by arvgta** [comment]
Hey Woeps!

Thanks for the reply!

Just to make sure we're comparing "apples with apples" ;-)
- http://4nf.org/ajaxify_globalEval.js - the old version with a
  
  $.globalEval()
- http://4nf.org/ajaxify.js - the new version with a normal
  
  eval()

It'd be great, if the new version works, but that would mean there is a bug in

```
$.globalEval()
```

Looking forward to your results :)

Kind regards

**Comment by arvgta** [comment]
I've reverted to using the

```
$.globalEval()
```

because there were complaints, that inline scripts no longer worked at the global level.

@woeps && @faisalrehmanid :

The only thing I can hope for is to spot a business rule for the bug and pre-process the inline script accordingly.  That would be elegant and add value...

Thanks for both of your help!

So can we spot a regularity in the errors?

Otherwise, what I suppose I could do is something like this (cryptive but not elegant):

```
function _addtext(t) {
    try {
        $.globalEval(t);
    } catch (e) {
        try { 
           eval(t);
        } catch (e) {
            $.log("Error in inline script : " + t + "\nError code : " + e);
        }
    }
}
```

(**activated for the time being**)

**Comment by arvgta** [comment]
Please re-open, especially, if someone can specify a pre-processing rule...
