### ISSUE TITLE
Documentation lacks navigation

### ISSUE THREAD

**Issue by wolph** [arvgta/ajaxify#4]
The documentation looks very pretty and seems useful so far, but it's quite annoying that I have to click back to the index page before I can visit the next page in the documentation.

Perhaps consider using sphinx-doc.org for documentation?

**Comment by arvgta** [comment]
Thank again!

I'm currently using Wordpress and very happy with it.  Can sphinx-doc.org be used "within" it?

I might downsize 4nf.org to devote it to this plugin entirely and completely overhaul the navigation correspondingly, because there is virtually no interest in "PageRank Bar" or "Minimialist Google Analytics...".  What do you think?

Sorry, in a bit of a hurry today...

**Comment by wolph** [comment]
I am not aware of any integration, but since it generates html output it shouldn't be too hard to integrate.
Usually I just put my Sphinx documentation on readthedocs. Example: http://mailjet.readthedocs.org/en/latest/

**Comment by arvgta** [comment]
Solved by downsizing http://4nf.org/

Is it better now?

Thanks and 
Kind regards

**Comment by wolph** [comment]
Yes, brilliant :)

That solves it perfectly
